### ISSUE TITLE
still appear

### ISSUE THREAD

**Issue by andrioktaviyan** [mrinc/F-B-Hide-Recommendations-and-Reels#111]
still appear on me , not working

**Comment by mrinc** [comment]
What still appears ?  

There are a few things we cleanup - please provide more info and pics/html for me?

**Comment by artogahr** [comment]
Hi @mrinc ! First of all thank you for the great extension. 
I actually came here after realizing "Wait why have I been doomscrolling Facebook shorts again, wasn't they disabled?" :D 

This person probably also just clicked the "Report an issue" button, but don't know much about Github issues or the OSS community. 

Anyway, for a little while there it seems the extension wasn't working, but right now I refreshed the page and shorts are blocked again. All's well on my side.

**Comment by mrinc** [comment]
Thanks!  

Most likely, which is why I asked for more info so I can work out their issue :)   
Should probs add a issue template ... one day lol  

Yea, FB has been doing changes as they always do which has caused some fun.  
I am pushing an updated version (seems auto-release failed) which should have some good fixes on it (like speeding up the initial run time)
